name: tfsec

on:
  push:
    branches:
      - prod
      - dev
      - staging

jobs:
  tfsec:
    name: Run tfsec sarif report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec
        run: |
          tfsec . --format sarif --out tfsec.sarif || true

      - name: Upload tfsec sarif report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec.sarif
